<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="basem-PC" ignored="1" name="Test_Cases" tests="2" failures="1" timestamp="2023-12-17T14:47:27 EET" time="65.288" errors="0">
  <testcase name="TC_01" time="28.241" classname="Shopping_Cart.TC_01_Add_Product_To_Shopping_Cart"/>
  <testcase name="TC_02" time="30.509" classname="My_Account.TC_02_Click_Save_Without_Add_New_First_And_Last_Name">
    <failure type="java.lang.AssertionError" message="expected [You should enter new first and last name before saving] but found [The customer info has been updated successfully.]">
      <![CDATA[java.lang.AssertionError: expected [You should enter new first and last name before saving] but found [The customer info has been updated successfully.]
at My_Account.TC_02_Click_Save_Without_Add_New_First_And_Last_Name.TC_02(TC_02_Click_Save_Without_Add_New_First_And_Last_Name.java:45)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC_02 -->
  <testcase name="@AfterTest Close_browser" time="0.0" classname="Base_Class.Base_Class">
    <ignored/>
  </testcase> <!-- @AfterTest Close_browser -->
</testsuite> <!-- Test_Cases -->
